### ISSUE TITLE
Crashing on startup with Satisfactory, "Can't find module SML" error

### ISSUE THREAD

**Issue by Pantheris2019** [satisfactorymodding/SatisfactoryModManager#106]
I tried to launch my game recently after moving my game, and it tells me it "Can't find module SML," I have tried now reinstalling the game, reinstalling the mod manager, having the game moved to its default directory so that the entire installation was redone, and I cannot fix this error.  I need help, I cannot play mods anymore, please fix this ASAP so I can start on my next video.

**Comment by mircearoata** [comment]
### Update
Experimental has been merged into Early Access so the version SMM 2.4.3 worked with doesn't exist anymore, so I reenabled the update. Make sure SMM finds the correct version of the game (should start with 152, instead of 151), so that it can get you SML 3.1.0, which works with this game version. If it doesn't show the correct version, try restarting your PC
