### ISSUE TITLE
satisfactory mod manager 2.4.3 will not load without updating and update 2.4.4 crashes game

### ISSUE THREAD

**Issue by crashdodgers** [satisfactorymodding/SatisfactoryModManager#109]
Right, this is the second time I have had this problem with the smm/sml file not being found. Yesterday after updating a couple of mods my save game crashed, then the mod manager update came through and now my game will not start at all, all I keep getting is the same blood message about the sml file not being found.

I have tried to uninstall and reinstall using 2.4.3, but when this loads up it automictically wants to update to 2.4.4, which crashes my game! How do I fix this problem?

**Comment by mircearoata** [comment]
Experimental has been merged into Early Access so the version SMM 2.4.3 worked with doesn't exist anymore, so I reenabled the update. Make sure SMM finds the correct version of the game (should start with 152, instead of 151), so that it can get you SML 3.1.0, which works with this game version. If it doesn't show the correct version, try restarting your PC
