### ISSUE TITLE
It says the setup has a virus in it.

### ISSUE THREAD

**Issue by spaceduckgamer** [satisfactorymodding/SatisfactoryModManager#117]
I don't know why because when I installed it for the first time it said there was no virus I'm wondering for the download at github and ficsit.app were hacked.
![Screenshot (92)](https://user-images.githubusercontent.com/84213684/124169868-bdc81500-da74-11eb-85fc-f132b966826e.png)
![Screenshot (91)](https://user-images.githubusercontent.com/84213684/124169892-c4ef2300-da74-11eb-83e7-e1a1f4d5dfc3.png)

**Comment by kulcris** [comment]
false positive most likely, but i am getting the same result

**Comment by Deathanatorx** [comment]
This happened to me too, dont worry. you have to switch browsers and make sure windows isnt in charge of security for that browser, like google. than try to download it again. Now its still gonna say "hey dude, this code gets access to a lotta stuff, are you sure you want this?" but it should ask rather than flat out deny. So confirm its what you want and your good to go! Hope this helps

**Comment by AstroFloof** [comment]
@spaceduckgamer @kulcris @Deathanatorx see issue #53
