### ISSUE TITLE
Only white screen after update to 2.5.0

### ISSUE THREAD

**Issue by hydrox** [satisfactorymodding/SatisfactoryModManager#118]
Since the update to v2.5.0 the ModManager only shows a white screen

OS: Ubuntu 18.04.5

![Satisfactory Mod Manager](https://user-images.githubusercontent.com/113484/124350761-e4ae5480-dbf6-11eb-836c-f182f75ca310.png)

**Comment by fredmcdonald** [comment]
Confirm same issue with Linux Mint 19.3 Tricia. Satisfactory itself still loads correctly with mods.

**Comment by mircearoata** [comment]
Rosuav experienced the same issue and after some debugging, we found that basically any build coming from me would result in that. They then built SMM too, resulting in a slightly larger file size, all coming from the c++ modules. The released version was built under WSL Ubuntu 20.04, but I also built it on another machine (also Ubuntu 20.04 but bare metal, this was the machine I built the previous versions on). All 3 versions run fine on that machine. I expect Rosuav's build to work for both of you, but let me know if my build does too. I hope it does, otherwise I'll have to investigate the differences between my system and Rosuav's more. Links are below.

[Rosuav's build - Google Drive link](https://drive.google.com/file/d/1I3tJXgjmYhUmNWM5Nj1LicKbzRHAAx_-/view?usp=sharing)
[My build - Google Drive link](https://drive.google.com/file/d/15sv8Ko5OSEugtqZu-4sSyZhrzS-MM8dX/view?usp=sharing)

**Comment by fredmcdonald** [comment]
That worked for me, @mircearoata ! Thank you.

**Comment by hydrox** [comment]
Satisfactory-Mod-Manager_Rosuav-build.AppImage (96283343 bytes) -> Starting fine
Satisfactory-Mod-Manager_MirceaServer-build.AppImage (96094912 bytes) -> Starting fine
Satisfactory-Mod-Manager.AppImage (96069813 bytes) (from github release page) -> White Screen

**Comment by mircearoata** [comment]
Thank you! I replaced the release file now with my server build, so it should be fine for other people too.
Also, I realized that actually on the server I was building with the docker image for node, which came with Debian and, more importantly, gcc 6 rather than gcc 9 which I had in WSL, so that's most likely what made the difference in size and functionality.
