### ISSUE TITLE
Headless/Loader Methods for Dedicated Linux Servers (EA 5)

### ISSUE THREAD

**Issue by farvour** [satisfactorymodding/SatisfactoryModManager#131]
Hello! I was going to ask about this before but the game was still experimental and didn't expect much support for it. Now that it is EA, I'm sure modders will be interested in updating things. That being said, I know many mods probably haven't been updated yet, and possibly not even SML. However, I was wondering if anyone had any insight into installing them into the Dedicated Server for mods that likely require to run server-side (Passive Mode comes to mind). The Dedicated Server I'm using is Linux and thus using something like the SMM wouldn't be feasable and an automated way to install would be nice.

Let's use a use-case of: building the Dedicated Server as a Docker image. I have a quick little implementation of this going on over in my repo here https://github.com/farvour/satisfactory-dedicated-server but am curious how loading mods would work server-side with something like SMM.

I suppose this could be classified as "feature request"?

**Comment by farvour** [comment]
This seems to be related to tracking this issue: https://github.com/satisfactorymodding/SatisfactoryModLoader/issues/114 since it really is more in-line with what most folks running dedicated servers would want to use. Since SMM uses SML (and recommends not using it independently), I think more instructions would be in order for those using Linux Dedicated servers. Additionally, since many dedicated servers on Linux are going to be headless, a way to use SMM+SML combo through either the CLI or through configuration files would be ideal here.

**Comment by mircearoata** [comment]
Vilsol is working on a CLI SMM (made in go from scratch, as my SMM API is made in javascript, which isn't exactly the best for a small CLI executable). It will be able to manage SML and the mods in just the same way SMM does, handling the dependencies, keeping them up to date, etc.

There is also a project of a server web interface, https://github.com/mrhid6/SatisfactoryServerManager , which uses the existing SMM API for its mod managing page. I believe in its current state it works, but can't actually use mods since they aren't compatible with dedicated server build.

**Comment by mircearoata** [comment]
SMM3 has now released with support for remotely managing server mods
