### ISSUE TITLE
Issue with the SMM install guide for Linux users

### ISSUE THREAD

**Issue by AngelSkyheart** [satisfactorymodding/SatisfactoryModManager#136]
Source: https://ficsit.app/guide/9aDEJRdmJsEBTJ

>Do I need to install anything else?
Unless you run Linux, then no. Installing SMM will also install all the other things-

Me: Hey wait a second, I run Linux! Why does the guide just breeze past this, like 'buck Linux'?! I need to know what else to install! The amount of trouble this gave me the first time I was trying to install SMM on Zorin sucked! It's a good thing I was already part of this Discord server when it happened cause it was the only place I could find an answer!

**Comment by Ryder17z** [comment]
I just downloaded the appimage file and run it. Works like a charm for me.

**Comment by mircearoata** [comment]
I let Deantendo know that he has to update that guide. Since it was last updated in January 2021 I believe the guide was referring to the issue in SML 2.2.1 that the bootstrapper did not work properly under wine (it was trying to find the game root path and failed, so we had to hardcode the relative game root path). That, however, is no longer the case, we are not using the bootstrapper anymore, SMM works fine under linux, and SML does as well (under wine).
