### ISSUE TITLE
[Bug] Unable to run on Linux "fuse: device not found" when installed

### ISSUE THREAD

**Issue by Firjens** [satisfactorymodding/SatisfactoryModManager#142]
Hello.

I'm currently attempting to install the mod manager on a Linux server (Ubuntu 21). When attempting to execute the appimage I get the following:

```
root@satisfactory:~/Satismod# chmod +x Satisfactory-Mod-Manager.AppImage 
root@satisfactory:~/Satismod# ./Satisfactory-Mod-Manager.AppImage 
fuse: device not found, try 'modprobe fuse' first

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
root@satisfactory:~/Satismod# modprobe
modprobe: ERROR: missing parameters. See -h.
root@satisfactory:~/Satismod# modprobe fuse
modprobe: FATAL: Module fuse not found in directory /lib/modules/5.4.128-1-pve
```

I've never heard of modprobe, so I'm not sure if this is an issue with the OS, if I did something wrong but I followed the instructions provided on the release page.

**Comment by zpangwin** [comment]
Was looking through Linux-issues and saw this... I'm on Fedora 35 and the appImage works mostly fine for me aside from a couple of very minor issues (things like sort order getting messed up when switching and or the occasional mod not playing nice under certain profiles). Anyway, I had to deal with modprobe a few weeks back for something else I was doing so I thought I'd chime in... it's related to what kernel modules are currently loaded. I can 99% guarantee this is an OS config issue rather than something with SMM. I'm not sure what exactly you need for Ubuntu Server but you might check one of these out:

https://www.reddit.com/r/debian/comments/k1kt96/cannot_mount_appimage_please_check_your_fuse_setup/

https://askubuntu.com/questions/1188938/appimage-not-working

Alternately, I am fairly confident that it would not be an issue if you used another distro as long as it was something moderately recent. But if that's not an option and the above don't help, I'd try asking about that specific error on askubuntu.

**Comment by Firjens** [comment]
> Was looking through Linux-issues and saw this... I'm on Fedora 35 and the appImage works mostly fine for me aside from a couple of very minor issues (things like sort order getting stuck when I switch the view for "Show" switching and having to restart SMM before sorting will work correctly again or the occasional mod not playing nice under certain profiles). Anyway, I had to deal with modprobe several months back for something else completely unrelated that I had been working with (was related to writing programs inside server containers) so I thought I'd chime in... `modprobe` is related to what kernel modules are currently loaded. I can 99% guarantee this is an OS config issue rather than something with SMM. I'm not sure what exactly you need for Ubuntu Server but you might check one of these out:
> 
> https://www.reddit.com/r/debian/comments/k1kt96/cannot_mount_appimage_please_check_your_fuse_setup/
> 
> https://askubuntu.com/questions/1188938/appimage-not-working
> 
> Alternately, I am fairly confident that it would not be an issue if you used another distro as long as it was something moderately recent. But if that's not an option and the above doesn't help, I'd try asking about that specific error on askubuntu.

Hi,

Sorry for my late response. The server was headless and I chose to run it on a Windows server, not a fix but a workaround.

Regards

**Comment by mircearoata** [comment]
As zpangwin mentioned, AppImages require the FUSE module to run, as they contain a filesystem that needs to be mounted. The [AppImage wiki](https://docs.appimage.org/user-guide/troubleshooting/fuse.html#how-to-install-fuse) documents how to install FUSE, though I believe it should be already available on most recent distro versions
