### ISSUE TITLE
SMM incorrectly shows Experimental Build as Early Access.

### ISSUE THREAD

**Issue by JamieRCHI** [satisfactorymodding/SatisfactoryModManager#167]
There is a mod that was made specifically for U7 that SMM is saying is not compatible.
Which means, when installed I get a big Red colored start the game button.
Also any mods I add, I get a popup telling me I have an incompatible mod and wants me to remove it.

I am not sure if this is just an SML issue or an SMM issue, or both.

Workaround: I can just ignore the popup and leave the new mod alone (The mod that increases the size of the Blueprint Machine) and then when my mods are installed I close SMM and start Satisfactory from the Steam menu directly. The mods I have installed work fine.

(Note that I haven't tested the mod for the Blueprint machines but I am able to start U7 Experimental just fine.)

**Comment by mircearoata** [comment]
This happened because Steam decided recently to change the case of the `betakey` field in the library game entry to `BetaKey`. It is annoying, because it's not even the first time they randomly change the case like this, they did it for other fields before too...

There is a rewrite of SMM currently in progress, so I wasn't planning on making another release of the current version, but I might have to, for this.
