### ISSUE TITLE
Use viper for config

### ISSUE THREAD

**Issue by budak7273** [satisfactorymodding/SatisfactoryModManager#177]
Suggested by @mircearoata

**Comment by budak7273** [comment]
@mircearoata I think you already did this?

**Comment by mircearoata** [comment]
I have not, and I am not sure whether this would bring any benefit anymore. Initially I was thinking it would make saving the minimal config easier, but it turns out it does not skip default values when writing the config, and we also can't implement that on our own because viper does not expose the default values.

And then there's the problem of how to keep track of the data in viper. If we don't unmarshal the viper config to a struct, we'd end up with tons of magic strings, but if we do unmarshal it to the current (or a similar) struct, viper can't marshal it back, so we'd only use it as a glorified json.Unmarshal with default values support, which is something we already have.

Given all that, I think a better solution for us to only save default values would be to store a separate defaults object, and diff the current settings to that, returning a map with just the modified keys. I could not find any package that would do that yet (the diff packages return diff entries, rather than an object with the modified fields), but implementing this ourselves should not be too difficult, since we diff the same type against itself, meaning virtually zero edge cases or conversion, simply walking the reflected type would be enough.
