### ISSUE TITLE
Installation of Satisfactory Mod Manager doesn't start

### ISSUE THREAD

**Issue by julan111** [satisfactorymodding/SatisfactoryModManager#186]
Hi, I'm trying to install the Satisfactory Mod Manager, but I can't start the installation process.

What I did:
1. I downloaded the File from https://ficsit.app/
2. Double clicked the file but nothing happens (No installation window opens, no error is shown, I also find no log entries).
3. Tried with V3.0.0 beta & V2.9.3 &V2.9.2.
4. Tried to launch the exe-File from my download-Folder as an admin
5. Tried adding it to allowed apps in Windows Defender Firewall (was listed as "Handles Satisfactory mods and mod loader")

My System:
- Windows 11 Home 64 bit
- AMD Ryzen 9 7900X 12-Core Processor               4.70 GHz
- 64 GB RAM

Thank you in advance vor your kind suggestions.

**Comment by julan111** [comment]
Satisfactory Update 8
Early Access - v0.8.3.3 - Build 273254

**Comment by Cranium6** [comment]
Have had this issue on two Windows devices as well, both Windows 11.
I was able to work around it by running it as a different user, and then grabbing the mods that I needed. Going to the appdata folder for the different user, and then copying over the files from AppData\Roaming\Satisfactory Mod Manager.exe\EBWebView into the same place on the user folder where I wanted to install the mods. I still can't launch the program, but at least I can run Satisfactory with the mods installed now.

**Comment by mircearoata** [comment]
Windows 11 is weirdly more strict about executables from the internet, without giving any proper message on that. We had to add a Windows 11 section to the docs a while back, specifically because it would just try to open the executable in something, instead of just actually running it. Maybe it's a similar issue, that can be fixed by unblocking the file in the file properties? https://docs.ficsit.app/satisfactory-modding/latest/ForUsers/SatisfactoryModManager.html#Install_Win11

**Comment by julan111** [comment]
Thank you very much @Cranium6 for your kind advice. Unfortunately running it through a different user didn't help.

But unblocking the file worked!! 👌🕺
Thanks a lot, @mircearoata

**Comment by julan111** [comment]
Unblocking the file in the file properties helped.

Thanks to all the contributors
