### ISSUE TITLE
Using the install button on the website doesn't work properly with SMM3

### ISSUE THREAD

**Issue by Th3Fanbus** [satisfactorymodding/SatisfactoryModManager#188]
Haven't tried reproducing, but https://discord.com/channels/555424930502541343/555782140533407764/1205991804995113040

Pressing the Install button on the website seems to pass `9mwuEBapJ7orMt` to SMM (error is intentional, to show the `smmanager://` URL):

![image](https://github.com/satisfactorymodding/SatisfactoryModManager/assets/22937129/fedda97d-e422-4762-9b2f-b7fc81b8c94a)

And SMM uses that as modref for some reason.

![image](https://github.com/satisfactorymodding/smr-frontend/assets/22937129/d57eb63b-fec1-4685-a8c3-bcb49b3602f9)

I believe the fix (get the modref from the mod files or similar) should be implemented in SMM.

**Comment by mircearoata** [comment]
SMM has always expected the mod reference in the URI, since it does not work in any way with mod IDs. It looks like all install buttons (the one on the mod card in the mods list and on the home page, and the ones in the mod version "tab"), except for the ones in the latest version section of the mod details, which specifically passes the modID, because it was previously a download button, and this was missed when turning it into an install button https://github.com/satisfactorymodding/smr-frontend/blob/staging/src/lib/components/mods/ModLatestVersions.svelte#L54
