### ISSUE TITLE
[v3] Rename Server Listing

### ISSUE THREAD

**Issue by Merith-TK** [satisfactorymodding/SatisfactoryModManager#201]
I have two servers that use different mod packs, 
They both show up as "DS (Remote X)" in the list with no way of telling which server is which, even when selected becasue the loaded profile is not stored on the server, meaning there is a risk that when I connect to one of these servers, I will inadvertently, overwrite all the mods with the wrong profile (as per-default actions in the mod manager) and break the save
![image](https://github.com/satisfactorymodding/SatisfactoryModManager/assets/10422110/edcd92d1-f0e7-4c12-bd74-3de05d203004)
![image](https://github.com/satisfactorymodding/SatisfactoryModManager/assets/10422110/1fd4c4c1-33c3-4f27-9811-1c15d5a9fd34)

**Comment by mircearoata** [comment]
This has been requested before, though I don't think an issue was made for it, so now at least it's tracked for others to see as well.

I am planning to add this in the next beta version, and adding this would also allow for redacting the address in the dialog without making the entries indistinguishable.

Regarding overwriting the mods with the wrong profile, that should not happen, because SMM remembers the selected profile per install, so selecting the server install would apply the profile that was last used on it, which should result in no changes assuming no changes were made to the profile.

**Comment by Merith-TK** [comment]
The problem I ran into was when i would select a server, it would retain the selected profile and try 
Screenshot of initial launch
![image](https://github.com/satisfactorymodding/SatisfactoryModManager/assets/10422110/20706d34-63b0-4dcc-b733-b928a8ccb8b4)

if I select a server that is not the current profile it goes to "default",  which deleted all the mods
![image](https://github.com/satisfactorymodding/SatisfactoryModManager/assets/10422110/9b210097-03ef-4a9b-9a43-e0a6ced38c73)
They were existing *before* I did this

**Comment by mircearoata** [comment]
That should not be the case, unless the previously used profile was deleted, or when removing and readding a server, because SMM stores the last selected profile for each install, it doesn't try to apply the one that was shown in the dropdown before choosing the install.

https://github.com/satisfactorymodding/SatisfactoryModManager/assets/19414258/72de0c66-af47-4131-a33a-9d2388c73808

Can you attach the SMM log?
