### ISSUE TITLE
Latest Apple mage does not run on Kubuntu 24.04

### ISSUE THREAD

**Issue by steve7233** [satisfactorymodding/SatisfactoryModManager#207]
Mod manager is giving me a blank white screen just now. It worked last month when I last used it. I downloaded the latest Apple version and it would not run. I ran in a console and got the following output:

> [20896:0729/001355.723018:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_Satisf5uwaGi/chrome-sandbox is owned by root and has mode 4755.

**Comment by mircearoata** [comment]
So following from https://github.com/satisfactorymodding/SatisfactoryModManager/issues/206#issuecomment-2255031584 neither the SMM3 beta (not an appimage, using webkit2gtk), nor SMM2 (an appimage, using chromium) works?

Also, it's not Apple, it's App Image, a file format that embeds dependencies into the executable so that it will run without any dependency setup on any linux machine

Try running the appimage with `--no-sandbox` or `--disable-setuid-sandbox`

**Comment by PhoneDroid** [comment]
@mircearoata 
- `--no-sandbox` works
- `--disable-setuid-sandbox` doesn't

**Comment by mircearoata** [comment]
Closing this as SMM3 is now released
