### ISSUE TITLE
WebView2

### ISSUE THREAD

**Issue by SatisfactoryBug** [satisfactorymodding/SatisfactoryModManager#256]
Please stop using WebView2 [SMM Previous like v2.9.0 etc never needed WebView2] as i don't want WebView2 of Microsoft crazy 725MB....... I never use WebView2 but SMM WON'T open Unless Forced to use WebView2

Thank You

**Comment by mircearoata** [comment]
SMM v2 didn't need WebView2 because it was using electron, which bundles chromium, like what Discord, Slack. VSCode, WhatsApp, and so many more apps. Even Steam and Epic use a bundled chromium, though not electron. This means you end up with multiple GBs of the same version of chromium on your PC, one for each electron/bundled chromium app you use. Having so many different chromium instances installed is also a security risk, since each app would have to keep releasing updates with newer versions of electron/chromium when security patches in those are released.

SMM v3's core is no longer written in javascript for performance and compatibility reasons, but the UI is still portable. So instead of electron, it uses wails, which serves the same purpose as electron, but instead of bundling chromium, it uses WebView2, which can be installed only once, and then shared with other apps that use it (for example PowerToys, Modrinth, Outer Wilds Mod Manager, and more). WebView2 is not the Edge browser, it's just the chromium engine, but with the Edge naming.

Not using WebView2 is therefore not an option, and the only alternative would be to bundle WebView2, but that would mean adding the 500MB of WebView2 to the SMM download, which can't be shared with other apps.

**Comment by budak7273** [comment]
Use ficsit-cli if you refuse to use SMM
