### ISSUE TITLE
If any servers are enabled, non-server mods cannot be installed

### ISSUE THREAD

**Issue by jf647** [satisfactorymodding/SatisfactoryModManager#265]
I have a dedicated server set up, but I also regularly download my save and run in singleplayer mode (I have a "designer" save with all the AGS cheats turned on that I use to create blueprints.)

Some mods are not marked as being compatible with servers.  So long as I have a dedicated server configured anywhere, I cannot install those mods.

Example: https://ficsit.app/mod/CurveBuilder

If I try to install this even when I have selected my "Steam" installation and my "Si!gle Player Only" profile, I get the error "You can't install this mod.  Reason: This mod does not support one or more of your installs."

[Image](https://github.com/user-attachments/assets/28f10178-9b08-47de-b0f3-1e98e39b51c0)

This seems like a overly strict restriction, as there is no technical reason why I can't run that mod but only when in single player.

Can we get either a mapping from profile to "enabled installations" (such that I could exclude my dedicated server from the "Single Player Only" profile) or a force install (with the appropriate admonishment dialog)?

**Comment by mircearoata** [comment]
SMM already only considers the installs that have that profile selected for the compatibility check. As that message says, "this mod doesn't support one or more of your installs *that use profile X*", so check which profile you assigned to the `Server 1` install.

There is no way to "force install", because you'd just get an actual error instead of that message when attempting to install the mod. The only way to "bypass" a mod not being supported on the server is if the mod specifies that it is only required locally (which can mean either server or client only, depending on what it supports)
