### ISSUE TITLE
Impossible for friends to join after using Satisfactory Mod Manager and uninstalling it

### ISSUE THREAD

**Issue by hb0nes** [satisfactorymodding/SatisfactoryModManager#51]
To my dismay, my friends can't join my game. Even when I remove the entire mod manager and all mods, this still occurs.
Has my save game been altered? I verified my game files through steam, everything seems in order, but they can't join my vanilla game because it mentions them not having Satisfactory Mod Manager.

**Comment by mircearoata** [comment]
It mentions them not having Satisfactory Mod **Loader** which is not the same as SMM. Uninstalling SMM doesn't remove the mods and the mod loader, so install SMM back, and switch to the vanilla profile so that it removes all the mods and the mod loader. If it still says 1 mod loaded in the main menu, switch to the modded profile and back to vanilla, some files might have been not deleted when doing it the first time.

**Comment by hb0nes** [comment]
I was on vanilla when it said this. However, I removed the loader myself
from the game files, which worked.
