### ISSUE TITLE
Updater just uninstalled, no update performed.

### ISSUE THREAD

**Issue by Sakata-MC** [satisfactorymodding/SatisfactoryModManager#55]
Updater needs to ironing. It uninstalled itself, then happily went away.
I got home, saw a green "update me" button, pressed it.
remove_old  I believe was the program that requested UAC, it (failed to) remove the shortcut on the desktop (probably doesn't need to anyways, just patch in place). then it just... stopped.

Hopefully a one-off bug.  Another foss app that might help with a good updater is CKAN, if it's around still.

**Comment by mircearoata** [comment]
It happens for "all users" installs, I think because it tries to update, but doesn't ask for admin, then asks for admin only for uninstaller but not for the installer. It started happening probably when I made it silently update instead of showing the full installer. It might be an issue with electron-update, but I couldn't find any issue for this on the electron-builder repo.

**Comment by picoshmit** [comment]
happend the same to me today, good luck the lastes version is fix

**Comment by mircearoata** [comment]
This is fixed in v2.1.2 so future updates won't have this issue
