### ISSUE TITLE
SMM finds Satisfactory but  then says this, Satisfactory install was found, but it points to a folder that doesn't exist.

### ISSUE THREAD

**Issue by lbauerr** [satisfactorymodding/SatisfactoryModManager#82]
So I can't load mods. I did just clone and install a new C: drive and H: drive (where steam is located).

Then here is the Debug (shortened) report on the error

2021-03-07 13:12:50:045	[INFO]	Set debug mode to false
2021-03-07 13:12:52:169	[DEBUG]	Epic Games Launcher is not installed

This is a Steam Experimental install. 

Any help getting SMM to find and load Satisfactory would be appreciated! I have played this game for many hours.

**Comment by mircearoata** [comment]
Mods don't currently work on Experimental, and because of the latest patch on EXP, the path to the exe SMM needs to get the game version from on Steam doesn't exist anymore (from `FactoryGame\Binaries\Win64\FactoryGame-Win64-Shipping.exe` it turned into `Engine\Binaries\Win64\UE4Game-Win64-Shipping.exe`), so SMM gives the generic invalid install message. It will be fixed when mods will work on the new engine version

**Comment by lbauerr** [comment]
Thanks, it was driving me nuts 😉

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
